name: Build and Push Spigot Image

on:
  push:
    branches: [ main ]
    tags:
      - v*

env:
  VERSION: 1.18

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/ttys0/spigot:latest
            ghcr.io/ttys0/spigot:${{ env.VERSION }}
