name: Spigot Image Build

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  VERSION: 1.18.1
  IMAGE_NAME: spigot

jobs:
  build-amd64:
    runs-on: [self-hosted, linux, AMD64]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Spigot Image
        run: docker build . --file Dockerfile --tag "${IMAGE_NAME}-amd64" --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/"${IMAGE_NAME}-amd64"

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          
          docker tag $IMAGE_NAME $IMAGE_ID:${{ env.VERSION }}
          docker push $IMAGE_ID:${{ env.VERSION }}


  build-arm64:
    runs-on: [self-hosted,linux,ARM64]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Spigot Image
        run: docker build . --file Dockerfile --tag "${IMAGE_NAME}-arm64" --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID_ARM64="${IMAGE_ID}-arm64"
          echo IMAGE_ID_AMD64="${IMAGE_ID}-amd64"
        
          docker tag $IMAGE_NAME $IMAGE_ID_AMD64:${{ env.VERSION }}
          docker push $IMAGE_ID_ARM64:${{ env.VERSION }}
          
      
          docker manifest create --amend $IMAGE_ID:${{ env.VERSION }} $IMAGE_ID_AMD64:${{ env.VERSION  }} $IMAGE_ID_ARM64:${{ env.VERSION }} 
          docker manifest push $IMAGE_ID:${{ env.VERSION }}

 
            
  
